### ISSUE TITLE
Issues when running on the web server

### ISSUE THREAD

**Issue by kevin199011** [ambj/MuPeXI#5] opened 2017-08-24 06:09 UTC
Hi, I have a somatic mutation filtered VCF file generated by GATK haplotypeCaller. I used that file to run MuPeXI on the web server, but got the following errors. Could you please let me know what's wrong with this? Thank you!

Traceback (most recent call last):
  File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 1577, in 
    main(sys.argv[1:])
  File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 78, in main
    peptide_info, peptide_counters, fasta_printout, pepmatch_file_names = peptide_extraction(peptide_length, vep_info, proteome_reference, genome_reference, reference_peptides, reference_peptide_file_names, input_.fasta_file_name, paths.peptide_match, tmp_dir, input_.webserver, input_.print_mismatch, input_.keep_temp, input_.prefix, input_.outdir, input_.num_mismatches)
  File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 667, in peptide_extraction
    peptide_info, pepmatch_file_names = normal_peptide_correction(mutated_peptides_missing_normal, mutation_info, p_length, reference_peptide_file_names, peptide_info, peptide_match, tmp_dir, pepmatch_file_names, webserver, print_mismatch, num_mismatches)
  File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 772, in normal_peptide_correction
    assert mutated_peptide in peptide_info
AssertionError

Kevin

**Comment by ambj** [comment] 2017-08-24 13:10
Hi Kevin

This is most likely due to incompatibility between VEP version, reference and/or the genomic reference used when calling the variants.
Check all your references; are they all fx GRCh38 version 85? is the ensembl VEP installation also version 85?
As a note I would recommend using MuTect2 as variant caller, since this is the GATK combination of MuTect and HaplotypeCaller.

Best,
Anne-Mette

On Aug 24, 2017, at 08:09, kevin199011 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I have a somatic mutation filtered VCF file generated by GATK haplotypeCaller. I used that file to run MuPeXI on the web server, but got the following errors. Could you please let me know what's wrong with this? Thank you!

Traceback (most recent call last):
File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 1577, in
main(sys.argv[1:])
File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 78, in main
peptide_info, peptide_counters, fasta_printout, pepmatch_file_names = peptide_extraction(peptide_length, vep_info, proteome_reference, genome_reference, reference_peptides, reference_peptide_file_names, input_.fasta_file_name, paths.peptide_match, tmp_dir, input_.webserver, input_.print_mismatch, input_.keep_temp, input_.prefix, input_.outdir, input_.num_mismatches)
File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 667, in peptide_extraction
peptide_info, pepmatch_file_names = normal_peptide_correction(mutated_peptides_missing_normal, mutation_info, p_length, reference_peptide_file_names, peptide_info, peptide_match, tmp_dir, pepmatch_file_names, webserver, print_mismatch, num_mismatches)
File "/usr/cbs/bio/src/MuPeXI-1.1/MuPeXI/MuPeXI.py", line 772, in normal_peptide_correction
assert mutated_peptide in peptide_info
AssertionError

Kevin

**Comment by kevin199011** [comment] 2017-08-24 13:59
Hi Anne-Mette, the genome reference I used is GRCh38, release-90.
I pasted part of the head and result part here for format reference:

##fileformat=VCFv4.2
##FILTER=<ID=LowQual,Description="Low quality">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  TUMOR
1       946247  .       G       A       102.28  PASS    AC=2;AF=1.00;AN=2;DP=3;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;QD=34.09;SOR=1.179 GT:AD:DP:GQ:PL  1/1:0,3:3:9:130,9,0
1       953259  .       T       C       90.28   PASS    AC=2;AF=1.00;AN=2;DP=3;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;QD=30.09;SOR=2.833 GT:AD:DP:GQ:PL  1/1:0,3:3:9:118,9,0
1       953279  .       T       C       98.28   PASS    AC=2;AF=1.00;AN=2;DP=3;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;QD=32.76;SOR=2.833 GT:AD:DP:GQ:PL  1/1:0,3:3:9:126,9,0
1       1014274 .       A       G       219.80  PASS    AC=2;AF=1.00;AN=2;DP=7;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;QD=31.40;SOR=0.941 GT:AD:DP:GQ:PL  1/1:0,7:7:21:248,21,0

Thank you

Kevin

**Comment by ambj** [comment] 2017-08-28 08:33
Hi Kevin 
I just ran the bit of the vcf file you have sent, without an error ocuring, on the web server. 
With the information you have given me so far, and since i'm not able to reproduce the error, I'm unfortunately not able to solve the problem your experiencing. 
Best, 
Anne-Mette

**Comment by elakatos** [comment] 2018-01-18 15:41
Dear Anne-Mette,
I ran into the same issues, and found that the error might not come up from just a chunk of the data. In my case I managed to find one single line that lead to the issue (and the issue happens both on the server and on my local machine).
Below is the vcf file that reproduces the error. When the last line is deleted, there are no errors anymore. Can you help me what could be the issue with that one particular line? (It's the only problematic one out of 50000.)

Best,
Eszter

-------------------------------------------------------------------

##fileformat=VCFv4.2
##FILTER=<ID=alt_allele_in_normal,Description="Evidence seen in the normal sample">
##FILTER=<ID=clustered_events,Description="Clustered events observed in the tumor">
##FILTER=<ID=germline_risk,Description="Evidence indicates this site is germline, not somatic">
##FILTER=<ID=homologous_mapping_event,Description="More than three events were observed in the tumor">
##FILTER=<ID=multi_event_alt_allele_in_normal,Description="Multiple events observed in tumor and normal">
##FILTER=<ID=panel_of_normals,Description="Seen in at least 2 samples in the panel of normals">
##FILTER=<ID=str_contraction,Description="Site filtered due to contraction of short tandem repeat region">
##FILTER=<ID=t_lod_fstar,Description="Tumor does not meet likelihood threshold">
##FILTER=<ID=triallelic_site,Description="Site filtered because more than two alt alleles pass tumor LOD">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AF,Number=1,Type=Float,Description="Allele fraction of the event in the tumor">
##FORMAT=<ID=ALT_F1R2,Number=1,Type=Integer,Description="Count of reads in F1R2 pair orientation supporting the alternate allele">
##FORMAT=<ID=ALT_F2R1,Number=1,Type=Integer,Description="Count of reads in F2R1 pair orientation supporting the alternate allele">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=FOXOG,Number=1,Type=Float,Description="Fraction of alt reads indicating OxoG error">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=QSS,Number=A,Type=Integer,Description="Sum of base quality scores for each allele">
##FORMAT=<ID=REF_F1R2,Number=1,Type=Integer,Description="Count of reads in F1R2 pair orientation supporting the reference allele">
##FORMAT=<ID=REF_F2R1,Number=1,Type=Integer,Description="Count of reads in F2R1 pair orientation supporting the reference allele">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
##INFO=<ID=ECNT,Number=1,Type=String,Description="Number of events in this haplotype">
##INFO=<ID=HCNT,Number=1,Type=String,Description="Number of haplotypes that support this variant">
##INFO=<ID=MAX_ED,Number=1,Type=Integer,Description="Maximum distance between events in this active region">
##INFO=<ID=MIN_ED,Number=1,Type=Integer,Description="Minimum distance between events in this active region">
##INFO=<ID=NLOD,Number=1,Type=String,Description="Normal LOD score">
##INFO=<ID=PON,Number=1,Type=String,Description="Count from Panel of Normals">
##INFO=<ID=RPA,Number=.,Type=Integer,Description="Number of times tandem repeat unit is repeated, for each allele (including reference)">
##INFO=<ID=RU,Number=1,Type=String,Description="Tandem repeat unit (bases)">
##INFO=<ID=STR,Number=0,Type=Flag,Description="Variant is a short tandem repeat">
##INFO=<ID=TLOD,Number=1,Type=String,Description="Tumor LOD score">
##SAMPLE=<ID=NORMAL,SampleName=TCGA-CK-5913-10A-01D-1650-10,File=/var/lib/cwl/job578910639_input_CAP7qw/TCGA-CK-5913-10A-01D-1650-10_hg19_Illumina_gdc_realn.bam>
##reference=file:///var/lib/cwl/job578910639_reference/GRCh38.d1.vd1.fa
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr7	986527	.	C	A	.	PASS	ECNT=1;HCNT=22;MAX_ED=.;MIN_ED=.;NLOD=27.62;TLOD=10.35	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:93,0:0.00:0:0:.:2406,0:49:44	0/1:57,6:0.081:5:1:0.167:1457,187:32:25
##chr7	1550183	rs566323218	G	A	.	PASS	DB;ECNT=1;HCNT=35;MAX_ED=.;MIN_ED=.;NLOD=6.71;TLOD=28.11	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:27,0:0.00:0:0:.:533,0:14:13	0/1:17,10:0.385:6:4:0.600:367,308:6:11
chr7	5987342	.	C	T	.	PASS	ECNT=1;HCNT=30;MAX_ED=.;MIN_ED=.;NLOD=34.15;TLOD=106.75	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:141,0:0.00:0:0:.:3797,0:69:72	0/1:77,47:0.386:25:22:0.468:2093,1428:37:40
chr7	6049896	.	AT	A	.	PASS	ECNT=1;HCNT=18;MAX_ED=.;MIN_ED=.;NLOD=20.71;RPA=6,5;RU=T;STR;TLOD=67.89	GT:AD:AF:ALT_F1R2:ALT_F2R1:QSS:REF_F1R2:REF_F2R1	0/0:83,0:0.00:0:0:2306,0:57:26	0/1:74,49:0.408:21:28:2105,1426:32:42

**Comment by ambj** [comment] 2018-01-30 09:11
Dear Eszter 
Thank you very much for making me aware of the error and for sending the problematic part of the VCF file this will make it much easier for me to trouble shoot the problem. Can i get you to send me the exact error messages you get as well? 
Best
Anne-Mette

**Comment by ambj** [comment] 2018-04-17 08:06
Dear Eszter 
I have not been able to reproduce the error with the newest version og MuPeXI on the development (dev) branch. This will be merged with the master in the new release by the end of this week. 
If you still see this error in your data - do not hesitate to contact me 

Best, 
/AM

**Closed** 2018-04-17 08:06 UTC
